#!/usr/bin/python3
"""This module contains a Rectangle class"""


class Rectangle:
    """Rectangle class"""

    def __init__(self, width=0, height=0):
        """Intantiation"""

        self.__width = width
        self.__height = height

    
    def width(self):

    pass